extensions:
 
  # TASKS
  - gruntfuggly.todo-tree

  # THEME
  - codercoder.codercoder-dark-theme

  # Live Server
  - ritwickdey.liveserver

  # Formatting
  - esbenp.prettier-vscode
  - dbaeumer.vscode-eslint
  - stylelint.vscode-stylelint
  - editorconfig.editorconfig

  # Nunjucks / Templates
  - ronnidc.nunjucks
 # - jinliming2.vscode-nunjucks
 # - monae.nunjucks

  # JavaScript / TypeScript
  - ms-vscode.vscode-typescript-next
  - christian-kohler.path-intellisense
  - christian-kohler.npm-intellisense

  # Sass / CSS
  - syler.sass-indented
  - mrmlnc.vscode-scss
  - zignd.html-css-class-completion

  # JSON / YAML / Markdown
  - redhat.vscode-yaml
 # - keesschollaart.vscode-json-validator
  - davidanson.vscode-markdownlint
  - yzhang.markdown-all-in-one

  # Shell / Scripts
  - timonwong.shellcheck
  - mads-hartmann.bash-ide-vscode
  - rogalmic.bash-debug

  # Env / Config
  - mikestead.dotenv

  # Docs / Design
  - figma.figma-vscode-extension
  - vstirbu.vscode-mermaid-preview
  - bierner.markdown-mermaid
  - pkief.material-icon-theme

  # SASS Dev
  - syler.sass-indented
  - jock.svg
  - glenn2223.live-sass

  # Git
  - eamodio.gitlens
  - mhutchie.git-graph

settings:
  editor.formatOnSave: true
  prettier.enable: true
  eslint.enable: true
  eslint.validate: ["javascript", "typescript"]
  shellcheck.enable: true
  shellcheck.useWorkspaceRootAsCwd: true
  gitlens.hovers.currentLine.over: "line"
  debug.node.autoAttach: "on"
  tasks.runners: ["pnpm run parallel"]
launch:
  configurations:
    - name: Debug vscode.sh
      type: bashdb
      request: launch
      program: "/vscode.sh"
      cwd: ""
      terminalKind: integrated
      args: []
